version: "3"
services:
  link-db:
    image: wqsacy/mongodb5
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
  api_dev:
    image: maurowcosta/api-ts
    ports:
      - "5000:3050"
    links:
      - link-db
  